### ISSUE TITLE
I get error after executing "./scripts/run-prod.sh"

### ISSUE THREAD

**Issue by barkbaek** [thereactivestack/kickstart#12]
=> Started proxy.                             
=> Started MongoDB.                           
                                              
/home/edmond/.meteor/packages/meteor-tool/.1.1.8.bc0nh3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: No element indexed by 16
    at ArraySet_at [as at] (/home/edmond/.meteor/packages/meteor-tool/.1.1.8.bc0nh3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/source-map/lib/source-map/array-set.js:83:11)
    at SourceMapConsumer_parseMappings [as _parseMappings] (/home/edmond/.meteor/packages/meteor-tool/.1.1.8.bc0nh3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/source-map/lib/source-map/source-map-consumer.js:225:44)
    at SourceMapConsumer.Object.defineProperty.get (/home/edmond/.meteor/packages/meteor-tool/.1.1.8.bc0nh3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/source-map/lib/source-map/source-map-consumer.js:160:14)
    at SourceMapConsumer_originalPositionFor [as originalPositionFor] (/home/edmond/.meteor/packages/meteor-tool/.1.1.8.bc0nh3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/source-map/lib/source-map/source-map-consumer.js:316:43)
    at /tools/isobuild/linker.js:408:25
    at Array.forEach (native)
    at Function._.each._.forEach (/home/edmond/.meteor/packages/meteor-tool/.1.1.8.bc0nh3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at [object Object]._.extend.getPrelinkedOutput (/tools/isobuild/linker.js:404:9)
    at /tools/isobuild/linker.js:117:27
    at Array.map (native)
    at Function._.map._.collect (/home/edmond/.meteor/packages/meteor-tool/.1.1.8.bc0nh3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:97:56)
    at [object Object]._.extend.getPrelinkedFiles (/tools/isobuild/linker.js:109:16)
    at Object.fullLink (/tools/isobuild/linker.js:724:31)
    at /tools/isobuild/compiler-plugin.js:641:28
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at [object Object]._.extend._linkJS (/tools/isobuild/compiler-plugin.js:640:18)
    at [object Object]._.extend.getResources (/tools/isobuild/compiler-plugin.js:510:48)
    at /tools/isobuild/bundler.js:718:37
    at Array.forEach (native)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:701:19)
    at /tools/isobuild/bundler.js:492:12
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:483:18)
    at /tools/isobuild/bundler.js:2062:14
    at /tools/isobuild/bundler.js:2150:20
    at Array.forEach (native)
    at Function._.each._.forEach (/home/edmond/.meteor/packages/meteor-tool/.1.1.8.bc0nh3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2149:7
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2047:31)
    at /tools/runners/run-app.js:551:36
    at time (/tools/tool-env/profile.js:232:28)
    at Function.run (/tools/tool-env/profile.js:377:12)
    at bundleApp (/tools/runners/run-app.js:541:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    at /tools/runners/run-app.js:396:12
____________________________________________________________________________
The above is my error log.
How can I fix this problem?

**Comment by barkbaek** [comment]
I'm using node v4.1.1 and npm 2.14.4

**Comment by eXon** [comment]
That's weird, I'm on linux (x64 though) and it is working fine. Have you tried with a fresh clone of this repo?

**Comment by eXon** [comment]
This was due to the source map. I've updated `webpack/production.config.js`.

Changing devtool to null should fix the problem for now.
