### ISSUE TITLE
run-prod

### ISSUE THREAD

**Issue by cybrix-revl** [thereactivestack/kickstart#9]
Hi,

This morning I started playing around with your kickstart codes. Being new to, Meteor and React it wasn't hard to get the dev working but when I run run-prod.sh, this is what I get:

```javascript
vagrant@vagrant:~/meteor-webpack-react-kickstart$ ./scripts/run-prod.sh
Hash: 130a21c722b259c4419a3d2fb5b2f9e23bfec0b9
Version: webpack 1.12.2
Child client:
    Hash: 130a21c722b259c4419a
    Version: webpack 1.12.2
    Time: 2728ms
      Asset     Size  Chunks             Chunk Names
    main.js  17.4 kB       0  [emitted]  main
        + 12 hidden modules

    WARNING in main.js from UglifyJs
    Side effects in initialization of unused variable sourceMap [./~/style-loader/addStyles.js:185,0]
    Side effects in initialization of unused variable media [./~/style-loader/addStyles.js:203,0]
    Condition always false [./~/style-loader/addStyles.js:23,0]
    Dropping unreachable code [./~/style-loader/addStyles.js:24,0]
    Condition always false [./~/style-loader!./~/css-loader!./react/todo/TodoApp.css:10,0]
    Dropping unreachable code [./~/style-loader!./~/css-loader!./react/todo/TodoApp.css:12,0]
    Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./react/todo/TodoApp.css:7,0]

    ERROR in ./~/css-loader!./react/todo/TodoApp.css
    Module build failed: ReferenceError: Promise is not defined
        at LazyResult.async (/home/vagrant/meteor-webpack-react-kickstart/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
        at LazyResult.then (/home/vagrant/meteor-webpack-react-kickstart/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
        at processCss (/home/vagrant/meteor-webpack-react-kickstart/node_modules/css-loader/lib/processCss.js:174:5)
        at Object.module.exports (/home/vagrant/meteor-webpack-react-kickstart/node_modules/css-loader/lib/loader.js:22:2)
     @ ./react/todo/TodoApp.css 4:14-81
Child server:
    Hash: 3d2fb5b2f9e23bfec0b9
    Version: webpack 1.12.2
    Time: 2718ms
      Asset     Size  Chunks             Chunk Names
    main.js  14.6 kB       0  [emitted]  main
        + 10 hidden modules

    ERROR in ./react/todo/TodoApp.css
    Module build failed: ReferenceError: Promise is not defined
        at LazyResult.async (/home/vagrant/meteor-webpack-react-kickstart/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
        at LazyResult.then (/home/vagrant/meteor-webpack-react-kickstart/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
        at processCss (/home/vagrant/meteor-webpack-react-kickstart/node_modules/css-loader/lib/processCss.js:174:5)
        at Object.module.exports (/home/vagrant/meteor-webpack-react-kickstart/node_modules/css-loader/lib/loader.js:22:2)
     @ ./react/todo/TodoApp.jsx 57:4-28
[[[[[ ~/meteor-webpack-react-kickstart/meteor ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
W20150926-15:41:09.969(0)? (STDERR) Warning: Location "/__webpack_hmr" did not match any routes
W20150926-15:41:19.333(0)? (STDERR) error while server-rendering Error: Cannot find module "./TodoApp.css"
W20150926-15:41:19.334(0)? (STDERR)     at react-build-generated/server/main.js:1:1253
W20150926-15:41:19.334(0)? (STDERR)     at [object Object].t.default.a.default.createClass.componentWillMount (react-build-generated/server/main.js:1:1335)
W20150926-15:41:19.334(0)? (STDERR)     at [object Object].chainedFunction [as componentWillMount] (packages/react-runtime-dev/react.browserify.js:5955:1)
W20150926-15:41:19.334(0)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (packages/react-runtime-dev/react.browserify.js:6804:1)
W20150926-15:41:19.334(0)? (STDERR)     at [object Object].wrapper [as mountComponent] (packages/react-runtime-dev/react.browserify.js:13941:1)
W20150926-15:41:19.335(0)? (STDERR)     at Object.ReactReconciler.mountComponent (packages/react-runtime-dev/react.browserify.js:14758:1)
W20150926-15:41:19.335(0)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (packages/react-runtime-dev/react.browserify.js:6823:1)
W20150926-15:41:19.335(0)? (STDERR)     at [object Object].wrapper [as mountComponent] (packages/react-runtime-dev/react.browserify.js:13941:1)
W20150926-15:41:19.335(0)? (STDERR)     at Object.ReactReconciler.mountComponent (packages/react-runtime-dev/react.browserify.js:14758:1)
W20150926-15:41:19.335(0)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (packages/react-runtime-dev/react.browserify.js:6823:1)
```

Ubuntu 14.04 on Vagrant
Node: v0.10.25
NPM: 1.3.10

```
meteor-webpack-react-kickstart@0.2.0 /home/vagrant/meteor-webpack-react-kickstart
├── babel-core@5.8.25
├── babel-loader@5.3.2
├── babel-plugin-react-transform@1.1.1
├── css-loader@0.19.0
├── es6-promise@3.0.2
├── file-loader@0.8.4
├── node-sass@3.3.3
├── null-loader@0.1.1
├── react@0.13.3
├── react-transform-catch-errors@1.0.0
├── react-transform-hmr@1.0.1
├── redbox-react@1.1.1
├── sass-loader@2.0.1
├── style-collector-loader@0.1.0
├── style-loader@0.12.4
├── url-loader@0.5.6
├── webpack@1.12.2
├── webpack-dev-middleware@1.2.0
└── webpack-hot-middleware@2.2.0
```

Any idea what this could be?

**Comment by eXon** [comment]
Hey @cybrix-revl 

I'm very happy it was easy to use :).

I just saw an [issue on the css-loader that explains the problem you're having](https://github.com/webpack/css-loader/issues/144). It is because your local Node.js version is too old. 0.10 wasn't supporting Promise and it looks like the css-loader needs it. They might add a polyfill in the future but for now, you will need to update your Node.js or revert to an older version of css-loader.

Let me know if this is working

**Comment by cybrix-revl** [comment]
Oh my bad. Yes updating node was the solution.

That warning,

```
Warning: Location "/__webpack_hmr" did not match any routes
```

remained. Can I ignore this?

**Comment by eXon** [comment]
Yes. You got this warning because you had your browser in dev open before and it was trying to connect back. Nothing to worry about.
